// Sample community used by `npm run seed` and demo deployments. All people and
// organisations here are fictional.

// [name, role, type, headline, city, country, interests, seeking, verified, about, lookingFor]
export const MEMBERS = [
  ["Ada Okafor", "admin", "founder", "Founder @ HelioGrid — solid-state grid storage", "Lagos", "Nigeria", ["energy", "climate"], "investor,builder", 1,
    "Ex-grid engineer building storage that makes solar work after sunset across West Africa.", "A seed lead who understands hardware timelines, and two battery engineers."],
  ["Marcus Chen", "member", "investor", "Partner, Frontier Deep Tech Fund · Seed–Series A", "San Francisco", "USA", ["ai", "robotics", "space"], "founder", 1,
    "Fifteen years backing hard-tech founders. I write $1–5M cheques into teams with real technical edges.", "Ambitious teams tackling billion-person problems. A short, specific note beats a deck."],
  ["Priya Raman", "moderator", "researcher", "Longevity researcher · senolytics & epigenetic clocks", "Bangalore", "India", ["longevity", "biotech"], "founder,investor", 1,
    "Running a lab on cellular ageing. I also help moderate this community.", "Founders turning ageing research into therapies, and investors who get long timelines."],
  ["Liam Walsh", "member", "builder", "Robotics engineer · ex-autonomous trucking", "Sydney", "Australia", ["robotics", "ai", "mobility"], "founder", 0,
    "Spent six years getting robots to drive trucks. Now looking for the next hard problem.", "A founder in warehouse or agricultural robotics who needs a technical co-founder."],
  ["Sofia Martins", "member", "founder", "Building vertical farms for megacities", "São Paulo", "Brazil", ["food-water", "climate"], "investor,mentor", 0,
    "We grow leafy greens 40 floors up, using 95% less water.", "Mentors who have scaled physical operations, and climate-food investors."],
  ["Hannah Weiss", "member", "mentor", "3x founder, now angel & mentor", "Berlin", "Germany", ["ai", "work", "education"], "founder,student", 1,
    "Built and sold three software companies. Now I give back two afternoons a week.", "First-time founders who want an honest sounding board."],
  ["Omar Haddad", "member", "investor", "Family office · climate & water", "Dubai", "UAE", ["climate", "food-water", "energy"], "founder", 1,
    "Deploying patient capital into water security and clean energy across MENA.", "Founders in desalination, water reuse and long-duration storage."],
  ["Grace Liu", "member", "student", "Aerospace PhD student", "Toronto", "Canada", ["space", "quantum"], "mentor,researcher", 0,
    "Researching in-space propulsion. Dreaming of a lunar startup one day.", "Mentors in the space industry and a summer internship."],
  ["Noah Patel", "member", "operator", "COO, scaling hardware startups", "Austin", "USA", ["energy", "robotics"], "founder", 0,
    "Took two hardware companies from prototype to 500 staff.", "An early-stage hardware team that needs an operator."],
  ["Chloe Nguyen", "member", "builder", "Full-stack + ML · open to co-founding", "Melbourne", "Australia", ["ai", "longevity"], "founder", 0,
    "Shipping ML products for a decade. Ready to go all-in on something meaningful.", "A mission-driven founder in health or longevity."],
  ["James Carter", "member", "partner", "Head of Venture, global energy corp", "London", "UK", ["energy", "climate"], "founder,researcher", 1,
    "I run a corporate venture arm: pilots first, investment second.", "Startups ready for an industrial-scale pilot in the next 12 months."],
  ["Aiko Tanaka", "member", "founder", "BCI startup — non-invasive neural interfaces", "Singapore", "Singapore", ["bci", "biotech", "ai"], "investor,researcher", 0,
    "Building a headset that reads intent well enough to type with your mind.", "Neuroscience advisors and deep-tech investors in Asia."],
  ["Jordan Blake", "member", "creator", "Producer · science & future-tech podcasts", "Los Angeles", "USA", ["ai", "space", "philanthropy"], "founder,researcher", 0,
    "I turn complex science into stories people can't stop listening to.", "Founders and researchers with a story the world needs to hear."],
  ["Elena Vasquez", "member", "founder", "Founder, Orbital Sun — space-based solar power", "Los Angeles", "USA", ["space", "energy"], "investor,builder", 1,
    "Beaming clean power from orbit. Our first demo satellite launches next year.", "RF engineers and investors who think in decades."],
  ["Kwame Mensah", "member", "builder", "Propulsion engineer · ex-launch provider", "Los Angeles", "USA", ["space", "robotics"], "founder", 0,
    "Eight years testing rocket engines. Happy to review your propulsion plans.", "An early space team that needs propulsion expertise."],
  ["Rachel Kim", "member", "investor", "Angel investor · health & AI", "Los Angeles", "USA", ["longevity", "ai", "biotech"], "founder", 1,
    "Former physician, now angel investing in tools that keep people healthy longer.", "Pre-seed founders in preventive health and diagnostics."],
  ["Dev Sharma", "member", "builder", "ML infrastructure engineer", "San Francisco", "USA", ["ai", "quantum"], "founder,builder", 0,
    "I make big models cheaper to train and serve.", "A founding-engineer role at an AI company doing something new."],
  ["Olivia Park", "member", "founder", "Founder, Brightpath — AI tutors for every child", "San Francisco", "USA", ["education", "ai"], "investor,mentor", 0,
    "Former teacher building a personal tutor for the 250 million kids who can't afford one.", "Edtech mentors and impact-minded seed investors."],
  ["Ben Rosen", "member", "investor", "Seed investor · deep tech & robotics", "San Francisco", "USA", ["robotics", "ai", "work"], "founder", 1,
    "First cheques into robotics and automation teams.", "Technical founders automating dull, dirty and dangerous work."],
  ["Samira Nasser", "member", "researcher", "Fusion plasma physicist", "San Francisco", "USA", ["energy", "quantum"], "founder,investor", 0,
    "Working on compact fusion confinement. Curious about the startup path.", "Founders and investors in fusion who want a physicist's view."],
  ["Isabella Moreno", "member", "operator", "Operator · ex-COO, global bank innovation", "New York", "USA", ["digital-assets", "work"], "founder", 0,
    "I have built regulated products at scale and love helping founders navigate compliance.", "A fintech or digital-assets startup that needs an operator."],
  ["Tom Fischer", "member", "investor", "GP, digital assets & fintech fund", "New York", "USA", ["digital-assets", "ai"], "founder", 1,
    "Investing in the infrastructure for a more open financial system.", "Founders building real utility, not hype."],
  ["Nadia Petrova", "member", "founder", "Founder, Renew Bio — reversing tissue ageing", "New York", "USA", ["longevity", "biotech"], "investor,researcher", 0,
    "Spun out of a university lab to take partial reprogramming to the clinic.", "Longevity-focused investors and clinical advisors."],
  ["Chris Adeyemi", "member", "creator", "Science journalist · exponential tech", "New York", "USA", ["ai", "longevity", "space"], "researcher,founder", 0,
    "I write about the people building the future, honestly and without hype.", "Researchers and founders happy to go on the record."],
  ["Ethan Brooks", "member", "founder", "Founder, BuildBot — robots for construction sites", "Austin", "USA", ["robotics", "work"], "investor,builder", 0,
    "Construction productivity has been flat for 50 years. We're fixing that with robots.", "Robotics engineers and construction-tech investors."],
  ["Maya Singh", "moderator", "mentor", "Startup coach · 200+ founders mentored", "Austin", "USA", ["education", "work", "philanthropy"], "founder,student", 1,
    "Coaching founders through the messy middle. Also a moderator here.", "Founders who want accountability and a plan."],
  ["Lucas Martin", "member", "researcher", "Quantum computing researcher", "Toronto", "Canada", ["quantum", "ai"], "founder,investor", 0,
    "Building error-corrected qubits. Interested in quantum-for-chemistry startups.", "Founders who need quantum expertise, and investors exploring the space."],
  ["Zara Ahmed", "member", "student", "CS undergrad · AI safety", "Toronto", "Canada", ["ai", "education"], "mentor,founder", 0,
    "Final-year student researching how to make AI systems more reliable.", "A mentor and an internship at an AI startup."],
  ["Freya Collins", "member", "policy", "Innovation policy advisor", "London", "UK", ["ai", "climate", "philanthropy"], "researcher,founder", 0,
    "I help governments write rules that let good technology happen safely.", "Founders who want to shape regulation early."],
  ["Arjun Mehta", "member", "investor", "Partner, climate tech VC", "London", "UK", ["climate", "energy", "mobility"], "founder", 1,
    "Leading Series A rounds in decarbonisation.", "Climate founders with early commercial traction."],
  ["Harriet Stone", "member", "founder", "Founder, Skyline — electric regional aviation", "London", "UK", ["mobility", "energy"], "investor,builder", 0,
    "Nineteen-seat electric planes for short routes.", "Aerospace engineers and patient investors."],
  ["Jonas Keller", "member", "builder", "Battery cell engineer", "Berlin", "Germany", ["energy", "mobility"], "founder", 0,
    "Designing sodium-ion cells for grid and EVs.", "A storage startup that needs cell design experience."],
  ["Lea Braun", "member", "founder", "Founder, H2Local — green hydrogen for industry", "Berlin", "Germany", ["energy", "climate"], "investor,partner", 0,
    "Making green hydrogen cheap enough for steel and chemicals.", "Industrial partners for a pilot, and seed investors."],
  ["Layla Al-Mansouri", "member", "partner", "Innovation director, sovereign fund", "Dubai", "UAE", ["ai", "energy", "space"], "founder,investor", 1,
    "Scouting frontier technology for national-scale deployment.", "Startups ready to deploy in the Gulf."],
  ["Karim Saleh", "member", "founder", "Founder, ClearWave — low-energy desalination", "Dubai", "UAE", ["food-water", "energy"], "investor,partner", 0,
    "Cutting the energy cost of fresh water by half.", "Utility partners and water-focused investors."],
  ["Rohan Iyer", "member", "founder", "Founder, FieldEye — drones for smallholder farms", "Bangalore", "India", ["food-water", "robotics", "ai"], "investor,mentor", 0,
    "Crop monitoring that works for a farmer with two acres and a phone.", "Agritech investors and a mentor who has scaled in rural India."],
  ["Ananya Rao", "member", "builder", "Full-stack engineer · digital health", "Bangalore", "India", ["longevity", "ai"], "founder", 0,
    "Building health apps used by millions. Open to a founding role.", "A health or longevity founder who needs a technical partner."],
  ["Vikram Nair", "member", "mentor", "Former CTO, now advisor", "Bangalore", "India", ["ai", "work", "education"], "founder,student", 1,
    "Led engineering at two unicorns. Now I help first-time technical founders.", "Technical founders scaling their first team."],
  ["Mei Lin Tan", "member", "investor", "Family office · longevity & biotech", "Singapore", "Singapore", ["longevity", "biotech", "philanthropy"], "founder", 1,
    "Funding science that adds healthy years to life.", "Longevity founders with strong scientific foundations."],
  ["Daniel Lim", "member", "operator", "Head of Operations, scale-up", "Singapore", "Singapore", ["work", "mobility"], "founder", 0,
    "I build the systems that let startups grow without breaking.", "A Series A company expanding across Asia."],
  ["Emily Clarke", "member", "founder", "Founder, Southern Launch Labs", "Sydney", "Australia", ["space", "robotics"], "investor,builder", 0,
    "Building small launch vehicles in Australia for the Asia-Pacific market.", "Propulsion engineers and space investors."],
  ["Josh Turner", "member", "student", "Mechatronics student · robotics club lead", "Sydney", "Australia", ["robotics", "ai", "space"], "mentor,founder", 0,
    "Building robots since I was twelve. Graduating next year.", "Internships at a robotics or space startup."],
  ["Sarah O'Brien", "member", "investor", "Angel investor · climate & mobility", "Sydney", "Australia", ["climate", "mobility", "energy"], "founder", 1,
    "Former founder, now backing Australian climate tech.", "Local founders raising their first round."],
  ["Will Harris", "member", "researcher", "Synthetic biologist", "Melbourne", "Australia", ["biotech", "food-water"], "founder,investor", 0,
    "Engineering microbes to make proteins without farms.", "Founders commercialising precision fermentation."],
  ["Ruby Walker", "member", "creator", "Documentary maker · future of humanity", "Melbourne", "Australia", ["space", "climate", "philanthropy"], "founder,researcher", 0,
    "Making films about the people solving humanity's grand challenges.", "Stories worth filming, and partners to fund them."],
  ["Mateo Rossi", "member", "investor", "Principal, LATAM climate fund", "São Paulo", "Brazil", ["climate", "food-water", "energy"], "founder", 1,
    "Backing climate founders across Latin America.", "Seed and Series A founders in food, water and energy."],
  ["Beatriz Costa", "member", "researcher", "Agronomist · regenerative agriculture", "São Paulo", "Brazil", ["food-water", "climate"], "founder", 0,
    "Measuring soil carbon at scale.", "Founders who need field-research partners."],
  ["Tunde Bakare", "member", "builder", "Payments engineer · digital assets", "Lagos", "Nigeria", ["digital-assets", "ai"], "founder", 0,
    "Built payment rails used by millions of Nigerians.", "A founding-engineer role in African fintech."],
  ["Amara Eze", "member", "founder", "Founder, SunBox — pay-as-you-go solar", "Lagos", "Nigeria", ["energy", "climate"], "investor,partner", 0,
    "Bringing power to homes the grid never reached.", "Impact investors and distribution partners."],
  ["Kenji Watanabe", "member", "researcher", "Humanoid robotics researcher", "Tokyo", "Japan", ["robotics", "ai"], "founder,investor", 0,
    "Teaching robots to learn from watching people.", "Founders building general-purpose robots."],
  ["Wanjiru Kamau", "member", "founder", "Founder, GreenLoop — circular plastics", "Nairobi", "Kenya", ["climate", "philanthropy"], "investor,mentor", 0,
    "Turning plastic waste into building materials across East Africa.", "Mentors and climate investors."],
];

export const REGION_FOR_CITY = {
  'San Francisco': 'sf-bay-area', 'Los Angeles': 'los-angeles', 'New York': 'new-york', Austin: 'austin', Toronto: 'toronto',
  London: 'london', Berlin: 'berlin', Dubai: 'dubai', Bangalore: 'bangalore', Singapore: 'singapore', Sydney: 'sydney',
  Melbourne: 'melbourne', 'São Paulo': 'sao-paulo', Lagos: 'lagos',
};

// [author, hub, kind, title, body, hoursAgo, comments: [author, body, hoursAgo][]]
export const POSTS = [
  ["Marcus Chen", "global-online", "discussion", "What does a great first message to an investor look like?",
    "I get a lot of requests. The best ones are short: who you are, what you're building, why me specifically. What works for you?", 6,
    [["Hannah Weiss", "Traction first, then the ask. And make it easy to say no.", 3], ["Olivia Park", "I always mention one specific thing from their portfolio. Gets replies.", 2]]],
  ["Maya Singh", "global-online", "discussion", "Welcome! Introduce yourself here 👋",
    "Tell us who you are, where you're based, and the moonshot you're working on (or want to work on).", 72,
    [["Zara Ahmed", "Zara, Toronto, AI safety student. Looking for a mentor!", 60], ["Wanjiru Kamau", "Wanjiru from Nairobi, turning plastic waste into bricks. Glad to be here.", 40], ["Kenji Watanabe", "Kenji, Tokyo. Humanoid robots. Happy to help anyone in robotics.", 20]]],
  ["Liam Walsh", "sydney", "discussion", "Sydney robotics & AI drinks — who's in?",
    "Thinking of a monthly casual meetup. I've posted an event, but also want to hear what format people prefer.", 30,
    [["Josh Turner", "Count me in. Lightning talks would be great.", 25], ["Emily Clarke", "Yes! Happy to host one at our workshop.", 20]]],
  ["Sarah O'Brien", "sydney", "offer", "Office hours for Sydney climate founders",
    "I'm doing 30-minute office hours every Friday for anyone raising a pre-seed or seed round in climate. Connect with me and say hi.", 50, []],
  ["Chloe Nguyen", "melbourne", "ask", "Looking for: a longevity founder who needs a technical co-founder",
    "Ten years of ML and full-stack. I want to spend the next ten on healthy lifespan. Tell me what you're building.", 20,
    [["Will Harris", "Not longevity exactly, but let's grab a coffee.", 10]]],
  ["Ruby Walker", "melbourne", "offer", "Filming founders for a documentary series",
    "I'm making a series on Australian moonshot builders. If you'd like to be considered, reply with a line about your work.", 90, []],
  ["Elena Vasquez", "los-angeles", "ask", "Looking for: RF engineers for wireless power transmission",
    "We're hiring our first two RF engineers for space-based solar. LA-based preferred.", 12,
    [["Kwame Mensah", "Not RF, but I know two great folks from my old team. Will intro.", 8]]],
  ["Jordan Blake", "los-angeles", "discussion", "Best moment from this week's Moonshots LIVE?",
    "For me it was watching the finalists pitch. What stuck with you?", 18,
    [["Rachel Kim", "The longevity panel. Rare to see science and business on one stage.", 15], ["Elena Vasquez", "Honestly, the hallway conversations.", 12]]],
  ["Olivia Park", "sf-bay-area", "ask", "Ask: intros to school districts piloting AI tutors",
    "We have strong results from 3 pilots and want 10 more districts this year.", 26, []],
  ["Samira Nasser", "sf-bay-area", "discussion", "Fusion: is the startup path real now?",
    "I'm a plasma physicist weighing a move from the lab to a startup. Would love to hear from people who've made the jump.", 40,
    [["Ben Rosen", "It's real, but pick your team carefully. Happy to chat.", 30], ["Dev Sharma", "Made a similar jump from academia. Best decision I've made.", 22]]],
  ["Tom Fischer", "new-york", "offer", "Offer: feedback on your tokenomics or fintech model",
    "Happy to spend an hour poking holes in your model before investors do.", 60, []],
  ["Nadia Petrova", "new-york", "ask", "Looking for: a clinical advisor for our first trial",
    "Partial reprogramming, moving toward our first-in-human study. Seeking an advisor with trial design experience.", 8,
    [["Rachel Kim", "Sending you a connection request, I may know someone.", 5]]],
  ["Ethan Brooks", "austin", "discussion", "Austin hardware founders: where do you prototype?",
    "We've outgrown our garage. Looking for shared machine-shop space.", 35,
    [["Noah Patel", "There's a great makerspace in East Austin. DM me.", 30]]],
  ["Lucas Martin", "toronto", "offer", "Offer: explaining quantum to your investors",
    "If you're pitching anything quantum, I'm happy to sanity-check the technical claims.", 80, []],
  ["Grace Liu", "toronto", "ask", "Ask: space internships for next summer?",
    "PhD student in propulsion. Open to anywhere, ideally Canada or the US.", 44,
    [["Emily Clarke", "We take interns in Sydney — worth a chat!", 30]]],
  ["Freya Collins", "london", "discussion", "What should AI regulation actually look like?",
    "I advise on policy and want founders' input: what rules would help rather than hurt?", 22,
    [["James Carter", "Clear sandboxes for pilots. Uncertainty is the real killer.", 18], ["Arjun Mehta", "Speed. Approval timelines matter more than the rules themselves.", 12]]],
  ["Harriet Stone", "london", "ask", "Looking for: battery engineers for electric aviation",
    "High energy density is everything for us. London or remote.", 55, []],
  ["Lea Braun", "berlin", "ask", "Seeking an industrial partner for a hydrogen pilot",
    "Our electrolysers are ready for a 1MW pilot. Looking for a steel or chemicals partner in Europe.", 16,
    [["James Carter", "Let's talk. This is exactly what our venture team pilots.", 10]]],
  ["Jonas Keller", "berlin", "discussion", "Sodium-ion vs lithium for grid storage — thoughts?",
    "Cheaper and safer, but lower density. For stationary storage, does density even matter?", 70,
    [["Ada Okafor", "For grid, cost per cycle is king. Sodium looks very promising.", 60]]],
  ["Karim Saleh", "dubai", "offer", "Offer: site visits to our desalination pilot",
    "Anyone in water tech is welcome to visit our pilot plant. Just connect with me.", 30, []],
  ["Layla Al-Mansouri", "dubai", "discussion", "What would you deploy at national scale tomorrow?",
    "If regulation and capital weren't barriers, what technology would you roll out first?", 48,
    [["Omar Haddad", "Water reuse. It's ready and the need is enormous.", 40], ["Karim Saleh", "Agreed. Biased, but agreed.", 38]]],
  ["Rohan Iyer", "bangalore", "ask", "Looking for: a mentor who has scaled in rural India",
    "FieldEye works with 3,000 farmers. We need to get to 300,000.", 24,
    [["Vikram Nair", "Happy to help. Let's set up a call.", 20]]],
  ["Ananya Rao", "bangalore", "discussion", "Health apps: what actually changes behaviour?",
    "We've built apps for millions of users. The ones that work all have one thing in common: a human in the loop.", 66, []],
  ["Mei Lin Tan", "singapore", "offer", "Longevity founders: our family office is investing",
    "We're writing seed and Series A cheques into longevity science. Science first, please.", 14, []],
  ["Daniel Lim", "singapore", "discussion", "Expanding into South-East Asia: lessons learned",
    "Six markets, six sets of rules. Happy to share our playbook — ask me anything.", 52,
    [["Aiko Tanaka", "Would love this. Which market did you start with?", 40]]],
  ["Mateo Rossi", "sao-paulo", "offer", "Offer: intro calls for LATAM climate founders",
    "Our fund is actively investing. Share what you're building.", 36,
    [["Sofia Martins", "Just sent you a request — would love your view on our Series A.", 30]]],
  ["Beatriz Costa", "sao-paulo", "discussion", "Can we measure soil carbon cheaply enough?",
    "Sampling costs are killing carbon markets for small farmers. What approaches are you seeing?", 90, []],
  ["Amara Eze", "lagos", "ask", "Looking for: distribution partners in northern Nigeria",
    "SunBox is in 20,000 homes in the south. We need partners to reach the north.", 28,
    [["Tunde Bakare", "Our payments network covers the north. Let's talk.", 20]]],
  ["Tunde Bakare", "lagos", "discussion", "Lagos builders meetup?",
    "Would anyone come to a monthly engineers-only meetup? No pitches, just building.", 75,
    [["Ada Okafor", "Yes please. I'll bring the HelioGrid team.", 60]]],
  ["Dev Sharma", "topic-ai", "offer", "Offer: ML infrastructure reviews for early-stage founders",
    "Happy to spend an hour reviewing your training or serving stack. Pre-seed and seed only.", 20,
    [["Olivia Park", "Taking you up on this!", 10]]],
  ["Zara Ahmed", "topic-ai", "discussion", "Which AI safety problems should startups work on?",
    "Research labs cover a lot, but what's commercially viable and actually useful?", 58, []],
  ["Nadia Petrova", "topic-longevity", "discussion", "The biggest bottleneck in longevity isn't science",
    "It's the lack of approved endpoints for ageing. Curious how others are approaching trials.", 34,
    [["Priya Raman", "Biomarkers of ageing are getting there. Epigenetic clocks especially.", 28], ["Mei Lin Tan", "This is why we fund biomarker work alongside therapies.", 20]]],
  ["Emily Clarke", "topic-space", "ask", "Looking for: propulsion engineers (Sydney or remote)",
    "Southern Launch Labs is hiring. Liquid engines, very hands-on.", 42,
    [["Kwame Mensah", "Very interested. Connecting now.", 30]]],
  ["Ada Okafor", "topic-energy", "discussion", "Storage is the real energy transition",
    "Generation is solved. Storing it cheaply is the whole game now. Change my mind.", 10,
    [["Samira Nasser", "Or make generation so abundant that storage matters less… fusion!", 6], ["Jonas Keller", "Storage. 100%.", 4]]],
  ["Arjun Mehta", "topic-climate", "offer", "What we look for in a climate Series A",
    "Clear unit economics, a path to 1 gigatonne, and a team that can build physical things.", 64, []],
  ["Ethan Brooks", "topic-robotics", "discussion", "Where will humanoid robots actually be useful first?",
    "My bet: construction sites and warehouses, not homes.", 18,
    [["Kenji Watanabe", "Agreed on warehouses. Homes are much harder.", 12], ["Liam Walsh", "Agriculture too — huge labour shortage.", 8]]],
  ["Will Harris", "topic-biotech", "discussion", "Precision fermentation costs are falling fast",
    "We're now under $10/kg for some proteins. Where should this go first?", 46, []],
  ["Lucas Martin", "topic-quantum", "discussion", "Quantum advantage for chemistry: when?",
    "My honest estimate is 5–7 years for useful chemistry simulations. Thoughts?", 88, []],
  ["Aiko Tanaka", "topic-bci", "ask", "Looking for: neuroscience advisors",
    "Our non-invasive BCI can decode typing intent. We need clinical neuroscience guidance.", 26,
    [["Priya Raman", "I can intro a colleague in neurology.", 20]]],
  ["Olivia Park", "topic-education", "discussion", "Will AI tutors replace or empower teachers?",
    "From our pilots: teachers who use them get more time for the human parts of teaching.", 38,
    [["Maya Singh", "Empower, every time. Love this.", 30]]],
  ["Isabella Moreno", "topic-work", "discussion", "The four-day week at startups: anyone tried it?",
    "Thinking of trialling it with my next team. Real experiences welcome.", 54, []],
  ["Karim Saleh", "topic-food-water", "discussion", "Water is the next great abundance story",
    "Desalination costs have fallen 10x. The next 10x is coming.", 30,
    [["Sofia Martins", "And farming is where it matters most.", 20]]],
  ["Harriet Stone", "topic-mobility", "discussion", "Electric aviation: regional first, then everywhere",
    "Short routes under 500km are ready now. Here's why.", 62, []],
  ["Tom Fischer", "topic-digital-assets", "discussion", "What's the most useful thing built on-chain this year?",
    "Beyond speculation, what have you actually used?", 44,
    [["Tunde Bakare", "Cross-border payments. Cheap and instant.", 40]]],
  ["Wanjiru Kamau", "topic-philanthropy", "discussion", "Where does philanthropy fit alongside venture?",
    "Some problems need grant money before they're investable. How do you think about it?", 70,
    [["Freya Collins", "Philanthropy can take the early risk that venture won't.", 60]]],
];

// [host, hub, title, description, daysAhead, startTime, endTime, venue, onlineUrl, capacity, going[], interested[]]
export const EVENTS = [
  ["Liam Walsh", "sydney", "Sydney robotics & AI night",
    "Casual drinks and three lightning talks on robotics and AI. All levels welcome — come say hi.", 5, "18:00", "20:30",
    "The Workshop, 12 Foster St, Surry Hills NSW", "", 60, ["Josh Turner", "Emily Clarke", "Sarah O'Brien"], ["Chloe Nguyen"]],
  ["Maya Singh", "global-online", "Founder office hours: raising your first round",
    "An open Q&A with mentors and investors from the community. Bring your questions — no pitching.", 3, "16:00", "17:00",
    "", "https://meet.example.com/founder-office-hours", 100, ["Olivia Park", "Rohan Iyer", "Zara Ahmed", "Hannah Weiss", "Amara Eze"], ["Wanjiru Kamau", "Grace Liu"]],
  ["Rachel Kim", "los-angeles", "Longevity founders dinner",
    "A small dinner for founders and researchers working on healthy lifespan. Limited to 12 seats.", 9, "19:00", "22:00",
    "Private dining room, Venice, Los Angeles", "", 12, ["Nadia Petrova", "Jordan Blake", "Elena Vasquez"], ["Chris Adeyemi"]],
  ["Elena Vasquez", "topic-space", "Space founders AMA: from lab to launch",
    "Three space founders share what they wish they'd known. Online, recorded for members.", 12, "17:00", "18:30",
    "", "https://meet.example.com/space-ama", null, ["Emily Clarke", "Kwame Mensah", "Grace Liu", "Josh Turner"], ["Harriet Stone"]],
  ["Ben Rosen", "sf-bay-area", "Robotics demo night",
    "Five early-stage robotics teams demo live. Investors and builders welcome.", 14, "18:30", "21:00",
    "Mission District, San Francisco", "", 80, ["Dev Sharma", "Samira Nasser", "Marcus Chen", "Olivia Park"], []],
  ["Tom Fischer", "new-york", "Digital assets breakfast",
    "Coffee and candid conversation about what's actually working in digital assets.", 6, "08:00", "09:30",
    "Flatiron, New York", "", 25, ["Isabella Moreno", "Chris Adeyemi"], ["Nadia Petrova"]],
  ["Noah Patel", "austin", "Hardware founders happy hour",
    "Meet other founders building physical things in Austin.", 8, "17:30", "19:30",
    "East Austin brewery (details on RSVP)", "", 40, ["Ethan Brooks", "Maya Singh"], []],
  ["Arjun Mehta", "london", "Climate tech breakfast",
    "Founders, investors and corporates talking decarbonisation over coffee.", 10, "08:00", "09:30",
    "King's Cross, London", "", 30, ["James Carter", "Freya Collins", "Harriet Stone"], []],
  ["Lea Braun", "berlin", "Hydrogen & storage meetup",
    "Short talks on green hydrogen and grid storage, then drinks.", 16, "18:30", "21:00",
    "Kreuzberg, Berlin", "", 50, ["Jonas Keller", "Hannah Weiss"], []],
  ["Omar Haddad", "dubai", "Water abundance roundtable",
    "A closed-door roundtable on water security across the Gulf.", 20, "18:00", "20:00",
    "DIFC, Dubai", "", 20, ["Karim Saleh", "Layla Al-Mansouri"], []],
  ["Vikram Nair", "bangalore", "Technical founders circle",
    "A monthly peer circle for technical first-time founders.", 7, "19:00", "21:00",
    "Indiranagar, Bangalore", "", 20, ["Rohan Iyer", "Ananya Rao", "Priya Raman"], []],
  ["Mei Lin Tan", "singapore", "Longevity science salon",
    "An evening of short talks on the science of ageing.", 18, "18:30", "21:00",
    "Tanjong Pagar, Singapore", "", 40, ["Aiko Tanaka", "Daniel Lim"], []],
  ["Chloe Nguyen", "melbourne", "AI builders coffee",
    "Casual Saturday coffee for people building with AI.", 4, "09:30", "11:00",
    "Fitzroy, Melbourne", "", 30, ["Will Harris", "Ruby Walker"], []],
  ["Mateo Rossi", "sao-paulo", "Climate founders drinks",
    "Informal drinks for climate founders and investors in São Paulo.", 11, "19:00", "21:30",
    "Vila Madalena, São Paulo", "", 40, ["Sofia Martins", "Beatriz Costa"], []],
  ["Tunde Bakare", "lagos", "Lagos builders meetup",
    "Engineers only. No pitches, just building and sharing.", 13, "17:00", "19:30",
    "Yaba, Lagos", "", 50, ["Ada Okafor", "Amara Eze"], []],
];

// [from, to, status, note]
export const CONNECTIONS = [
  ["Ada Okafor", "Omar Haddad", "accepted", "Omar — loved your talk on water abundance. HelioGrid could pair storage with desal. Would love 20 mins."],
  ["Sofia Martins", "Hannah Weiss", "accepted", "Hannah, I would really value mentorship as we plan our second vertical farm."],
  ["Chloe Nguyen", "Priya Raman", "pending", "Priya, I build ML pipelines and would love to help with your epigenetic clock work."],
  ["Liam Walsh", "Marcus Chen", "pending", "Marcus — robotics engineer exploring a warehouse-automation startup. Would value your perspective."],
  ["Olivia Park", "Marcus Chen", "pending", "Hi Marcus, Brightpath has strong pilot results in AI tutoring and we're raising a seed. Would love 15 minutes of your time."],
  ["Amara Eze", "Ada Okafor", "pending", "Ada, fellow Lagos energy founder here! Would love to compare notes on distribution and storage."],
  ["Kwame Mensah", "Ada Okafor", "pending", "Hi Ada, I'm a propulsion engineer who's curious about grid storage. Would love to learn more about HelioGrid."],
  ["Nadia Petrova", "Priya Raman", "pending", "Priya, your epigenetic clock work would be invaluable for our trial endpoints. Could we chat?"],
  ["Rachel Kim", "Nadia Petrova", "accepted", "Nadia, loved your post. I may know a clinical advisor for you."],
  ["Ben Rosen", "Ethan Brooks", "accepted", "Ethan, construction robotics is right in my wheelhouse. Let's talk."],
  ["Marcus Chen", "Elena Vasquez", "accepted", "Elena, space-based solar is fascinating. Would love to hear about your demo mission."],
  ["Marcus Chen", "Dev Sharma", "accepted", "Dev, always keen to meet great ML infra people."],
  ["Priya Raman", "Mei Lin Tan", "accepted", "Mei Lin, would love to share what our lab is seeing in senolytics."],
  ["Priya Raman", "Aiko Tanaka", "accepted", "Aiko, happy to connect you with neurology colleagues."],
  ["Vikram Nair", "Rohan Iyer", "accepted", "Rohan, let's get FieldEye to 300,000 farmers."],
  ["James Carter", "Lea Braun", "accepted", "Lea, our venture team would love to discuss a hydrogen pilot."],
  ["Arjun Mehta", "Harriet Stone", "accepted", "Harriet, electric aviation is on our radar. Let's connect."],
  ["Mateo Rossi", "Sofia Martins", "accepted", "Sofia, would love to learn about your Series A plans."],
  ["Tunde Bakare", "Amara Eze", "accepted", "Amara, our payments network could help your northern expansion."],
  ["Emily Clarke", "Kwame Mensah", "accepted", "Kwame, we'd love your propulsion expertise at Southern Launch Labs."],
  ["Josh Turner", "Liam Walsh", "accepted", "Liam, love the Sydney robotics meetup idea. Keen to help."],
  ["Sarah O'Brien", "Liam Walsh", "accepted", "Liam, if you start a robotics company, I'd love to hear about it early."],
  ["Maya Singh", "Olivia Park", "accepted", "Olivia, happy to be a sounding board as you raise."],
  ["Hannah Weiss", "Zara Ahmed", "accepted", "Zara, happy to mentor you — let's find a time."],
  ["Karim Saleh", "Layla Al-Mansouri", "accepted", "Layla, ClearWave is ready for national-scale deployment. Would love to chat."],
  ["Daniel Lim", "Aiko Tanaka", "accepted", "Aiko, happy to share our SEA expansion playbook."],
  ["Will Harris", "Chloe Nguyen", "accepted", "Chloe, fellow Melbourne builder. Coffee soon?"],
  ["Freya Collins", "James Carter", "accepted", "James, would love your view on pilot sandboxes."],
  ["Samira Nasser", "Ben Rosen", "accepted", "Ben, thanks for the encouragement on fusion. Would love to chat further."],
  ["Lucas Martin", "Grace Liu", "accepted", "Grace, fellow Toronto researcher. Let's grab lunch."],
  ["Jordan Blake", "Elena Vasquez", "accepted", "Elena, I'd love to feature Orbital Sun on the podcast."],
  ["Isabella Moreno", "Tom Fischer", "accepted", "Tom, happy to help your portfolio with compliance."],
  ["Beatriz Costa", "Mateo Rossi", "accepted", "Mateo, would love to discuss soil carbon measurement."],
  ["Wanjiru Kamau", "Hannah Weiss", "pending", "Hannah, I'd be grateful for your mentorship as GreenLoop grows."],
  ["Kenji Watanabe", "Ethan Brooks", "accepted", "Ethan, fascinating work on construction robots. Would love to compare notes."],
];

// [from, to, body, hoursAgo]
export const MESSAGES = [
  ["Omar Haddad", "Ada Okafor", "Great to connect, Ada. Are you in Dubai for the energy summit next month?", 72],
  ["Ada Okafor", "Omar Haddad", "I will be! Would love to show you our latest storage results.", 70],
  ["Omar Haddad", "Ada Okafor", "Perfect. Let's grab coffee on the Tuesday.", 5],
  ["Marcus Chen", "Elena Vasquez", "Elena, congrats on the demo mission news. Free for a call next week?", 30],
  ["Elena Vasquez", "Marcus Chen", "Thanks Marcus! Wednesday afternoon works. I'll send a deck beforehand.", 28],
  ["Mei Lin Tan", "Priya Raman", "Priya, your senolytics results are exciting. Could we set up a call with our science advisor?", 20],
  ["Rachel Kim", "Nadia Petrova", "Here's the clinical advisor I mentioned — introducing you both by email.", 4],
];
